### ISSUE TITLE
SRAG data

### ISSUE THREAD

**Issue by xmnlab** [FluVigilanciaBR/fludashboard#29]
@marfcg 
- What is the relationship between SRAG and ages values? In the examples bellow SRAG data is less than the sum of ages values. In the graphs, the y axis was named as "Incidência por 100 mil habitantes" in both Age and Incidence Chart.
- What does  SRAG information mean for "Brasil" State? should be the sum of the SRAG of all states for a specific week? In the example bellow, the SRAG of Brasil is less than SRAG of Acre.

``` python
In [11]: df[(df['Unidade da Federação'] == 'Brasil') & (df['DT_NOTIFIC_epiyearweek']=='2015W01')]
Out[11]: 
      DT_NOTIFIC_epiyearweek  UF  epiyear  epiweek      SRAG  0-4 anos  \
12493                2015W01  BR     2015        1  0.032282  0.169633   

       5-9 anos  10-19 anos  20-29 anos  30-39 anos          ...           \
12493   0.02535     0.01763    0.008763    0.020899          ...            

           mean       50%      2.5%     97.5%   L0   L1   L2   L3    Run date  \
12493  0.032282  0.032282  0.032282  0.032282  1.0  0.0  0.0  0.0  2016-10-19   

       Unidade da Federação  
12493                Brasil  

[1 rows x 24 columns]

In [12]: df[(df['Unidade da Federação'] == 'Acre') & (df['DT_NOTIFIC_epiyearweek']=='2015W01')]
Out[12]: 
    DT_NOTIFIC_epiyearweek  UF  epiyear  epiweek      SRAG  0-4 anos  \
719                2015W01  12     2015        1  0.248907  1.164836   

     5-9 anos  10-19 anos  20-29 anos  30-39 anos          ...           \
719       0.0         0.0         0.0         0.0          ...            

         mean       50%      2.5%     97.5%   L0   L1   L2   L3    Run date  \
719  0.248907  0.248907  0.248907  0.248907  1.0  0.0  0.0  0.0  2016-10-19   

     Unidade da Federação  
719                  Acre  

[1 rows x 24 columns]
```

**Comment by marfcg** [comment]
@xmnlab in the dataset all columns represent the incidence for the corresponding population, per 100 thousand.
This means that:

`x_j = C_j × 100000 / N_j`
where x_j is the incidence per 100 thousand, C_j is the reported number of cases and N_j is the population of that particular group.

In terms of absolute number of cases SRAG is in fact the sum of cases reported in all age groups for the same location, that is, 

`C_t = C_1 + C_2 + ...`

The reason why in the data it is not the sum is because of the above normalization, since we are reporting incidence and not absolute number of cases
- Example:

Suppose we have a population divided in two groups of 1000 (group 1) and 3000 (group 2) individuals, with 5 and 10 cases, respectively. The total population is 4000 and the total number of cases is 15. For each group and for the total, the incidence would be

`x_1 = 5×100000/1000 = 500`
`×_2 = 10×100000/3000 = 333.333`
`×_t = 15×100000/4000 = 375`

So you see that, while C_t=C_1+C_2, the same does not hold for the incidence x_t.

The same logic applies for the incidence in Brail compared to the incidence in each state. While the number of cases is given by the sum in each, the incidence is not.

**Comment by xmnlab** [comment]
@marfcg Thank you for the detailed explanation!!!
