### ISSUE TITLE
Figure "Dist. por Gênero e Idade" has no gender

### ISSUE THREAD

**Issue by fccoelho** [FluVigilanciaBR/fludashboard#42]
Add gender information by splitting the age bar into male and female.

Please check that missing cases are not being counted in the first age class (which is much higher than the rest)

**Comment by xmnlab** [comment]
@marfcg, 

have you have an estimated date to release gender information separated by age?

> Please check that missing cases are not being counted in the first age class (which is much higher than the rest)

@fccoelho, maybe this information has some sense (IMHO). When we are in the age to go to school or to work, generally we don't go to the hospital just because we have flu. But, when our kids has flu we need to take them to the hospital. Indeed, kindergartens do not accept the entrance of kids/babies with flu (maybe a origin of some kind of bias). So, we need the take them to the hospital and require some doctor's letter attesting to bring to the work.

Of course, I will check the information in the dataset :)

**Comment by marfcg** [comment]
I have checked the age distribution code and eyeballed a few samples from the data and it seems to be correct. I already knew that < 2 yo had a huge impact, but I was also impressed by the absurd difference.
By the way, the current age bracket used is how IBGE aggregates the yearly population estimate by State. For SRAG it would be better to have <2 yo as a separate bracket, but population estimates have only 0-4. It has yearly estimates by age only for the whole country, not by state (at least not that I could find so far).

All entries have non-empty age information (i.e., it's not a problem of NA -> 0), and the grouping is also working fine. I'll run more tests just to be thorough, but everything is looking fine as far as the code goes.

Regarding gender separation, I'm working on it today. I expect to have it ready by the end of the day. Even if unexpected difficulties arise, it should be ready on Monday.

Finally, regarding @xmnlab comment:
That's definitely the case for influenza-like illnesses. Nonetheless, here we are dealing with severe cases that lead to hospitalization, not only doctor consultation, so that aspect should be attenuated.
But still, it is known to affect infants with higher incidence than teenagers and young adults. That's one of the many reasons why they are targeted during vaccination campaign. Still, we weren't expecting that much of a difference. It's quite impressive.

**Comment by xmnlab** [comment]
@marfcg thank you for the explanation 👍  :)

**Comment by marfcg** [comment]
Sorry for the mess with close/reopen. 
The changes introduced fixes the issue as long as input data and notebook example goes. There's still the need to implement those changes into the dashboard.

**Comment by xmnlab** [comment]
don't worry .. This may have happened due to the text "fix + # issue number" 👍 
I'm working to update the dashboard.
