### ISSUE TITLE
Color code label to the map

### ISSUE THREAD

**Issue by xmnlab** [FluVigilanciaBR/fludashboard#77]
From @marfcg 

> I've just realized that we never added the color code label to the map (check InfoDengue's page for reference: https://info.dengue.mat.br/). In our case it's (for both "detalhado" and "resumido"):
> Atividade baixa (green)
> Atividade epidêmica (yellow)
> Atividade alta (orange)
> Atividade muito alta (red)

Do you talk about the info frame with this information?

In our map, we put that on the "i" button.  You should put the mouse over i button to see the legend.

**Comment by marfcg** [comment]
Sorry for the absurd delay on this.
The idea is to have a box like the one we see on the bottom right corner here:
![colorbar1](https://user-images.githubusercontent.com/8262366/30972805-020d2ed4-a442-11e7-9f15-a90f02e9a33c.png)

**Comment by xmnlab** [comment]
This box was created into the "I" button in the map controller ... It was done to use better the map area. If the legend box should be always ON .. maybe we should zoom out the map.

**Comment by marfcg** [comment]
I see your point.
For some reason it is not showing the colors on my screen, though... 
I believe it could be a good idea to have it always on at the bottom left side.
Alternatively, another option would be to have it clickable, instead of just becoming visible when placing to cursor above the "i" icon on the map. This way, we could start with it ON and the visitor could close it by clicking on the i icon.

**Comment by xmnlab** [comment]
> Alternatively, another option would be to have it clickable, instead of just becoming visible when placing to cursor above the "i" icon on the map. This way, we could start with it ON and the visitor could close it by clicking on the i icon.

This sounds good :)

**Comment by xmnlab** [comment]
@marfcg 

I test with a fixed legend box, change the window size .. and there is no overlapping 

so I will fix the legend box at the right bottom corner
